# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 34bf717141f166c3ecd5453661cfe6417f3a0e709803bb4c3477a96c44f46905c5bb0403dec9ac9c77067788f6c1b9b8b01bd141c4a2ae93c90cef34ccdf8c52

test:
  secret_key_base: 966e85ef71df6db1cce480ef7aaa67406e4604a8d9719f38fa3fa84389b2640642e7c2ced655225315b1dadff2e2cb5d95c6fe2c1fd15fae5ec7521271612d41

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
